builds:
  - binary: hpgo
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prelease: auto

universal_binaries:
  - replace: true

brews:
  - 
    name: hpgo
    homepage: https://github.com/jonathanc-n/hpgo
    tap:
      owner: jonathanc-n
      name: homebrew-tap
    commit_author:
      name: jonathanc-n
      email: chenleejonathan@gmail.com
  
checksum:
  name_template:'checksums.txt'