# .goreleaser.yaml
version: 2
project_name: hpgo

builds:
  - id: hpgo
    main: ./cmd/hpgo/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0

archives:
  - id: hpgo
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
    builds:
      - hpgo

release:
  github:
    owner: jonathanc-n
    name: hpgo
  # Move snapshots inside the release block
  snapshots:
    name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
